name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      

    # Ensure Docker is installed and set up
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_RAJNEET_USERNAME}}
        password: ${{ secrets.DOCKER_RAJNEET_PASSWORD}}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t ektuhi/dockerdemo2 .

    # Optionally, push the image to Docker Hub
    - name: Push the Docker image
      run: docker push ektuhi/dockerdemo2:latest --file Dockerfile
      if: github.event_name == 'push'
